### ISSUE TITLE
Unsubscribe?

### ISSUE THREAD

**Issue by aintnorest** [ericelliott/irecord#12]
I don't have any experience with RX and if it uses a weak maps or some other method for not needing an unsubscribe I apology for the question. Just curious how to unsubscribe once I have subscribed to an observable.

**Comment by ericelliott** [comment]
> In order to receive notifications from an observable collection, you use the subscribe method of Observable to hand it an Observer object. In return for this observer, the subscribe method returns a Disposable object that acts as a handle for the subscription. This allows you to clean up the subscription after you are done. Calling dispose on this object detaches the observer from the source so that notifications are no longer delivered. As you can infer, in RxJS you do not need to explicitly unsubscribe from an event as in the common JavaScript event model.

For more, see the RxJS [getting started](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/exploring.md) documentation.

**Comment by aintnorest** [comment]
Thank you for the link and the incredibly fast response. As well as the baby's first reaction article. Starting my second React project now and very excited to use factories instead of classes. More examples would be amazing especially using this tool but I'll muddle through, thank you again.

**Comment by ericelliott** [comment]
Sure. If you're interested in using factories for React, you should really consider using [react-stapmit](https://github.com/stampit-org/react-stampit).

I plan to write future articles discussing the benefits of stamps, and how React-Stampit can help replace the `React.createClass()` mixin mechanism.
