### ISSUE TITLE
Why is irecord not maintained?

### ISSUE THREAD

**Issue by nyrosmith** [ericelliott/irecord#13]
This sounds like a good approach so I am curious why it is no longer maintained?
Have you found a better approach or are there any troubles with the existing solution?

**Comment by ericelliott** [comment]
There is nothing wrong with it. I just don't currently have time to dedicate attention to it.

**Comment by nyrosmith** [comment]
Thanks for your fast answer!
I'll give it a try because it sounds really interessting
